"""init schema

Revision ID: 6b0638d3822c
Revises: 
Create Date: 2025-09-18 14:54:56.831924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0638d3822c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('vaches',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('date_dernier_village', sa.String(length=255), nullable=True),
    sa.Column('date_prochain_village', sa.String(length=255), nullable=True),
    sa.Column('date_insimination', sa.String(length=255), nullable=True),
    sa.Column('date_taghriz', sa.String(length=255), nullable=True),
    sa.Column('historique_medical_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lait_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vache_id', sa.String(length=255), nullable=False),
    sa.Column('quantite_lait_matin', sa.Float(), nullable=True),
    sa.Column('quantite_lait_soir', sa.Float(), nullable=True),
    sa.Column('somme_quantite', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=False),
    sa.Column('remarque', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vache_id'], ['vaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lait_productions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lait_productions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_lait_productions_vache_id'), ['vache_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lait_productions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lait_productions_vache_id'))
        batch_op.drop_index(batch_op.f('ix_lait_productions_date'))

    op.drop_table('lait_productions')
    op.drop_table('vaches')
    op.drop_table('users')
    # ### end Alembic commands ###
